language: node_js
node_js: stable

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g
  
deploy:
  provider: pages:git
  deploy_key: $GITHUB_TOKEN

after_script:
  - cd ./public
  - git init
  - git config user.name "jalen"
  - git config user.email "1152357479@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
 global:
   - GH_REF: github.com/SincerelyUnique/SincerelyUnique.github.io.git
   - secure: dVi2c6QDXQ284RBYaTRl5v18feXUO/YuBMFnBXB5GXF5TWli+QdKtzq8Zll6C0ut1V2+rTSrP5gK1sbbNZWnmAoy+H+A3qFKErAT94iZTgajOCywU42jOAgMBGi2+xUg+QX20kceVJmc9tA/LdWpNoRYbJ5+wOaLUWfiFzv7/3PtFDi+BwZVHkOaPwUaryQQW4M+5779i/fryREixZs8Y0gBqgBU01ySalbkarP2doorLDpopNP+OgAYgIzT8xHx+iiHnQsopt/x2f7mp3S1cx9a6Zh4gxUOMwRr/vKz/0iOouVHGA+pG7PlHzBaoTA9MHRXXqykCzxRfgZq45bovL3v0hVefOIKYjQikb7YvgVRDfhWESFXnJ4kmxQjxzaAgigGmbF/GZoJ9cyoS5yV3FywHjIYcGnEgFwF4wppONIeunYKeHmyheNycGvYzCd9/TBTSxnVGrgs/QyuAMF8dBHXrHtHORSk/wh89ZjTGTTzeYltmS6/lVezIgfs+iDKuGfLbIZSjPZkw+6mVXDadq6NZTluVmKZ6XotiudkAFrDvo5/2/jEmCCJbe4V5VLDps5vHTQul4KcWpQxNX5NYLmcqmWzNgabJ5lyA1M6rUsMUpFiRLbrpKeHU7b+5WlmsIEoSnDSpgZ6Jt+yqlunZ+2O6PMbgBrRtsK9/D8YrQw=
